import * as Popover from '@radix-ui/react-popover';
import { Check, Search, SlidersHorizontal, X } from 'lucide-react';
import { modelFamily } from '../lib/registry';
import type { GalleryState } from '../lib/url-state';
import type { Registry } from '../types';

export function CounterFilters({ registry, state, update }: { registry: Registry; state: GalleryState; update: (patch: Partial<GalleryState>, mode?: 'push' | 'replace') => void }) {
  const families = [...new Set(registry.configurations.map(config => modelFamily(config.model)))];
  const cuisines = registry.cuisines.filter(cuisine => registry.recipes.some(recipe => recipe.cuisines.includes(cuisine.id)));
  const lineages = [{ id: 'all', label: 'All lineages' }, { id: 'textbook', label: 'Textbook' }, { id: 'mothers', label: 'Mother’s' }, { id: 'hybrid', label: 'Hybrid' }];
  const count = Number(state.cuisine !== 'all') + Number(state.origin !== 'all');
  const segment = 'min-h-9 rounded-md border-0 bg-transparent px-2 text-sm font-medium text-slate-600 hover:bg-white aria-pressed:bg-white aria-pressed:text-blue-800 aria-pressed:shadow-sm';
  return <div className="counter-controls">
    <div className="flex flex-wrap items-center gap-3">
      <label className="flex h-11 min-w-48 flex-1 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 lg:max-w-sm"><Search size={16} className="shrink-0 text-slate-400" /><span className="sr-only">Search recipes</span><input className="min-h-0 w-full min-w-0 border-0 bg-transparent text-sm text-slate-800 outline-none" type="search" placeholder="Search recipes" value={state.query} onChange={event => update({ query: event.target.value }, 'replace')} /></label>
      <div className="flex flex-wrap items-center gap-1 rounded-lg bg-slate-200/60 p-1" role="group" aria-label="Filter by model"><button className={segment} aria-pressed={state.family === 'all'} onClick={() => update({ family: 'all', effort: 'all' })}>All models</button>{families.map(family => <button key={family} className={segment} aria-pressed={state.family === family} onClick={() => update({ family, effort: 'all' })}>{family}</button>)}</div>
      <Popover.Root><Popover.Trigger asChild><button className="inline-flex h-11 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 text-sm font-medium text-slate-700 hover:bg-slate-50" aria-label="Cuisine and lineage filters"><SlidersHorizontal size={16} />Filters{count > 0 && <span className="rounded bg-blue-50 px-1.5 text-xs text-blue-800">{count}</span>}</button></Popover.Trigger><Popover.Portal><Popover.Content side="bottom" align="end" sideOffset={8} collisionPadding={12} aria-label="Cuisine and lineage filters" className="z-40 max-h-[75dvh] w-80 max-w-[calc(100vw-1.5rem)] overflow-y-auto rounded-xl border border-slate-200 bg-white p-3 text-slate-800 shadow-xl focus:outline-none">
        {([{ key: 'cuisine', title: 'Cuisine', options: [{ id: 'all', label: 'All cuisines' }, ...cuisines] }, { key: 'origin', title: 'Lineage', options: lineages }] as const).map(group => <div key={group.key} role="group" aria-label={group.title} className="border-b border-slate-100 pb-2 last:border-0 last:pb-0"><p className="mb-1 mt-2 px-2 text-xs font-semibold text-slate-500">{group.title}</p>{group.options.map(option => <button key={option.id} aria-pressed={state[group.key] === option.id} onClick={() => update({ [group.key]: option.id })} className="flex min-h-10 w-full items-center justify-between gap-3 rounded-md border-0 bg-transparent px-2 py-2 text-left text-sm leading-snug text-slate-700 hover:bg-slate-100 aria-pressed:bg-blue-50 aria-pressed:text-blue-800">{option.label}{state[group.key] === option.id && <Check size={16} className="shrink-0" />}</button>)}</div>)}
      </Popover.Content></Popover.Portal></Popover.Root>
    </div>
    {state.family !== 'all' && <div className="mt-3 flex flex-wrap items-center gap-1" role="group" aria-label="Filter by thinking effort"><span className="mr-2 text-xs text-slate-500">Thinking</span><button className={segment} aria-pressed={state.effort === 'all'} onClick={() => update({ effort: 'all' })}>All efforts</button>{[...new Set(registry.configurations.filter(config => modelFamily(config.model) === state.family).map(config => config.reasoningEffort))].map(effort => <button key={effort} className={segment} aria-pressed={state.effort === effort} onClick={() => update({ effort })}>{effort}</button>)}</div>}
    {(state.harness !== 'all' || state.tier !== 'all') && <button className="mt-3 min-h-8 rounded-md border border-slate-200 bg-white px-2 text-xs text-slate-600" onClick={() => update({ harness: 'all', tier: 'all' })}>Clear saved harness / tier filter ×</button>}
    {count > 0 && <div className="mt-3 flex flex-wrap gap-2" aria-label="Active filters">{(['cuisine', 'origin'] as const).filter(key => state[key] !== 'all').map(key => { const label = key === 'cuisine' ? cuisines.find(item => item.id === state[key])?.label ?? state[key] : lineages.find(item => item.id === state[key])?.label ?? state[key]; return <button key={key} aria-label={`Remove ${label} filter`} onClick={() => update({ [key]: 'all' })} className="inline-flex min-h-8 items-center gap-2 rounded-md border border-slate-200 bg-white px-2 text-xs text-slate-600">{label}<X size={12} /></button>; })}</div>}
  </div>;
}
